# Generated by Django 3.1.7 on 2021-04-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.IntegerField(max_length=50)),
                ('subject', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
